// Generated by gencpp from file ros_basics_toturials/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_TOTURIALS_MESSAGE_ADDTWOINTS_H
#define ROS_BASICS_TOTURIALS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ros_basics_toturials/AddTwoIntsRequest.h>
#include <ros_basics_toturials/AddTwoIntsResponse.h>


namespace ros_basics_toturials
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ros_basics_toturials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_basics_toturials::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_basics_toturials::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ros_basics_toturials::AddTwoInts > {
  static const char* value()
  {
    return "ros_basics_toturials/AddTwoInts";
  }

  static const char* value(const ::ros_basics_toturials::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ros_basics_toturials::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::ros_basics_toturials::AddTwoInts > 
template<>
struct MD5Sum< ::ros_basics_toturials::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_toturials::AddTwoInts >::value();
  }
  static const char* value(const ::ros_basics_toturials::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_toturials::AddTwoIntsRequest> should match 
// service_traits::DataType< ::ros_basics_toturials::AddTwoInts > 
template<>
struct DataType< ::ros_basics_toturials::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_basics_toturials::AddTwoInts >::value();
  }
  static const char* value(const ::ros_basics_toturials::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_basics_toturials::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::ros_basics_toturials::AddTwoInts > 
template<>
struct MD5Sum< ::ros_basics_toturials::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_toturials::AddTwoInts >::value();
  }
  static const char* value(const ::ros_basics_toturials::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_toturials::AddTwoIntsResponse> should match 
// service_traits::DataType< ::ros_basics_toturials::AddTwoInts > 
template<>
struct DataType< ::ros_basics_toturials::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_basics_toturials::AddTwoInts >::value();
  }
  static const char* value(const ::ros_basics_toturials::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_BASICS_TOTURIALS_MESSAGE_ADDTWOINTS_H
